/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author xqq
 */
public class NewJFrame extends javax.swing.JFrame {
        float sum;
        String op="";
        int first = 0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn0P8 = new javax.swing.JButton();
        btnOP1 = new javax.swing.JButton();
        btnOP2 = new javax.swing.JButton();
        btnOP3 = new javax.swing.JButton();
        btnOP4 = new javax.swing.JButton();
        btnOP5 = new javax.swing.JButton();
        btnOP6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn0P8.setText(".");
        btn0P8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0P8ActionPerformed(evt);
            }
        });

        btnOP1.setText("+");
        btnOP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOP1ActionPerformed(evt);
            }
        });

        btnOP2.setText("-");
        btnOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOP2ActionPerformed(evt);
            }
        });

        btnOP3.setText("*");
        btnOP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOP3ActionPerformed(evt);
            }
        });

        btnOP4.setText("/");
        btnOP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOP4ActionPerformed(evt);
            }
        });

        btnOP5.setText("C");
        btnOP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOP5ActionPerformed(evt);
            }
        });

        btnOP6.setText("=");
        btnOP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOP6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn0P8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOP2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOP1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOP3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOP4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOP5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOP6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(177, 177, 177))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOP1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOP2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnOP5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOP3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn0P8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(btnOP6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

         //getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "1";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);// TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
//getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "2";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
//getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "3";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
//getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "4";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
//getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "5";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
  //getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "6";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
//getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "7";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
//getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "8";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
 //getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "9";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
//getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            str += "0";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);        // TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn0P8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0P8ActionPerformed
 // TODO add your handling code here:
            //getText()获取文本区域的值，赋值给str
            String str = txtResult.getText();
            //判断小数点是否存在
            if(str.indexOf(".") == -1){
            str += ".";
            //给文本区域对象txtResult设置显示内容
            txtResult.setText(str);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btn0P8ActionPerformed

    private void btnOP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOP1ActionPerformed
 //文本框没有数据，点击加号不执行加法操作
            String str = txtResult.getText();
            if(str.isEmpty()){
                //不执行操作
            }
            else{
                //文本框有数据，将文本框的内容转换成float类型，累加到sum变量
                float f = Float.parseFloat(str);
                if(first == 0){
                    sum = f;
                    first = 1;
                }
                else{
                    if(op == "+")
                        sum += f;
                    else if(op == "-")
                        sum -= f;
                    else if(op == "*")
                        sum *= f;
                    else if(op == "/")
                        sum /= f;
                }
                //把当前运算符存入一个临时变量
                    op = "+";
                //清空文本框，便于继续输入新的数值
                txtResult.setText("");
                
                
            }         // TODO add your handling code here:
    }//GEN-LAST:event_btnOP1ActionPerformed

    private void btnOP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOP6ActionPerformed
//先获取最后一次的运算符，执行对应的操作
            String str = txtResult.getText();
            float f = Float.parseFloat(str);
            if(op == "+")
                sum += f;
            else if(op == "-")
                sum -= f;
            else if(op == "*")
                sum *= f;
            else if(op == "/")
                sum /= f;
            txtResult.setText(sum + "");        // TODO add your handling code here:
    }//GEN-LAST:event_btnOP6ActionPerformed

    private void btnOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOP2ActionPerformed
        // TODO add your handling code here:
        //文本框没有数据，点击减号不执行减法操作
            String str = txtResult.getText();
            if(str.isEmpty()){
                //不执行操作
            }
            else{
                //文本框有数据，将文本框的内容转换成float类型
                float f = Float.parseFloat(str);
                if(first == 0){
                    sum = f;
                    first = 1;
                }
                else{
                    if(op == "+")
                        sum += f;
                    else if(op == "-")
                        sum -= f;
                    else if(op == "*")
                        sum *= f;
                    else if(op == "/")
                        sum /= f;
                }
                //把当前运算符存入一个临时变量
                    op = "-";
                //清空文本框，便于继续输入新的数值
                txtResult.setText("");  
            } 
    }//GEN-LAST:event_btnOP2ActionPerformed

    private void btnOP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOP3ActionPerformed
        // TODO add your handling code here:
        //文本框没有数据，点击加号不执行乘法操作
            String str = txtResult.getText();
            if(str.isEmpty()){
                //不执行操作
            }
            else{
                //文本框有数据，将文本框的内容转换成float类型
                float f = Float.parseFloat(str);
                if(first == 0){
                    sum = f;
                    first = 1;
                }
                else{
                    if(op == "+")
                        sum += f;
                    else if(op == "-")
                        sum -= f;
                    else if(op == "*")
                        sum *= f;
                    else if(op == "/")
                        sum /= f;
                }
                //把当前运算符存入一个临时变量
                    op = "*";
                //清空文本框，便于继续输入新的数值
                txtResult.setText("");
            } 
    }//GEN-LAST:event_btnOP3ActionPerformed

    private void btnOP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOP4ActionPerformed
        // TODO add your handling code here:
        //文本框没有数据，点击加号不执行加法操作
            String str = txtResult.getText();
            if(str.isEmpty()){
                //不执行操作
            }
            else{
                //文本框有数据，将文本框的内容转换成float类型，累加到sum变量
                float f = Float.parseFloat(str);
                if(first == 0){
                    sum = f;
                    first = 1;
                }
                else{
                    if(op == "+")
                        sum += f;
                    else if(op == "-")
                        sum -= f;
                    else if(op == "*")
                        sum *= f;
                    else if(op == "/")
                        sum /= f;
                }
                //把当前运算符存入一个临时变量
                    op = "/";
                //清空文本框，便于继续输入新的数值
                txtResult.setText("");
            } 
    }//GEN-LAST:event_btnOP4ActionPerformed

    private void btnOP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOP5ActionPerformed
        // TODO add your handling code here:
        sum = 0;
        first = 0;
        txtResult.setText("");
        op = "";
    }//GEN-LAST:event_btnOP5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn0P8;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnOP1;
    private javax.swing.JButton btnOP2;
    private javax.swing.JButton btnOP3;
    private javax.swing.JButton btnOP4;
    private javax.swing.JButton btnOP5;
    private javax.swing.JButton btnOP6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
